export const countiesSchema = {
  type: "Feature Layer",
  defaultVisibility: true,
  geometryType: "esriGeometryPolygon",
  allowGeometryUpdates: true,
  objectIdField: "OBJECTID",
  spatialReference: { wkid: 3857, latestWkid: 3857 },
  fields: [
    {
      name: "OBJECTID",
      type: "esriFieldTypeOID",
      alias: "ObjectId",
      sqlType: "sqlTypeOther",
      nullable: false,
      editable: false,
      domain: null,
      defaultValue: null,
    },
    {
      name: "STATE_FIPS",
      type: "esriFieldTypeString",
      alias: "State FIPS",
      sqlType: "sqlTypeOther",
      length: 2,
      nullable: true,
      editable: true,
      domain: null,
      defaultValue: null,
    },
    {
      name: "COUNTY_FIPS",
      type: "esriFieldTypeString",
      alias: "County FIPS",
      sqlType: "sqlTypeOther",
      length: 3,
      nullable: true,
      editable: true,
      domain: null,
      defaultValue: null,
    },
    {
      name: "FIPS",
      type: "esriFieldTypeString",
      alias: "FIPS",
      sqlType: "sqlTypeOther",
      length: 5,
      nullable: true,
      editable: true,
      domain: null,
      defaultValue: null,
    },
    {
      name: "NAME",
      type: "esriFieldTypeString",
      alias: "Name",
      sqlType: "sqlTypeOther",
      length: 50,
      nullable: true,
      editable: true,
      domain: null,
      defaultValue: null,
    },
  ],
};

export const indicatorsSchema = {
  type: "Feature Layer",
  defaultVisibility: true,
  objectIdField: "OBJECTID",
  fields: [
    {
      name: "OBJECTID",
      type: "esriFieldTypeOID",
      alias: "ObjectId",
      sqlType: "sqlTypeOther",
      nullable: false,
      editable: false,
      domain: null,
      defaultValue: null,
    },
    {
      name: "INDICATOR",
      type: "esriFieldTypeString",
      alias: "Indicator",
      sqlType: "sqlTypeOther",
      length: 50,
      nullable: true,
      editable: true,
      domain: null,
      defaultValue: null,
    },
    {
      name: "NAME_EN",
      type: "esriFieldTypeString",
      alias: "Name (English)",
      sqlType: "sqlTypeOther",
      length: 255,
      nullable: true,
      editable: true,
      domain: null,
      defaultValue: null,
    },
    {
      name: "NAME_ES",
      type: "esriFieldTypeString",
      alias: "Name (Spanish)",
      sqlType: "sqlTypeOther",
      length: 255,
      nullable: true,
      editable: true,
      domain: null,
      defaultValue: null,
    },
  ],
};

export const dataSchema = {
  type: "Feature Layer",
  defaultVisibility: true,
  objectIdField: "OBJECTID",
  fields: [
    {
      name: "OBJECTID",
      type: "esriFieldTypeOID",
      alias: "ObjectId",
      sqlType: "sqlTypeOther",
      nullable: false,
      editable: false,
      domain: null,
      defaultValue: null,
    },
    {
      name: "STATE_FIPS",
      type: "esriFieldTypeString",
      alias: "State FIPS",
      sqlType: "sqlTypeOther",
      length: 2,
      nullable: true,
      editable: true,
      domain: null,
      defaultValue: null,
    },
    {
      name: "COUNTY_FIPS",
      type: "esriFieldTypeString",
      alias: "County FIPS",
      sqlType: "sqlTypeOther",
      length: 3,
      nullable: true,
      editable: true,
      domain: null,
      defaultValue: null,
    },
    {
      name: "FIPS",
      type: "esriFieldTypeString",
      alias: "FIPS",
      sqlType: "sqlTypeOther",
      length: 5,
      nullable: true,
      editable: true,
      domain: null,
      defaultValue: null,
    },
    {
      name: "INDICATOR",
      type: "esriFieldTypeString",
      alias: "Indicator",
      sqlType: "sqlTypeOther",
      length: 50,
      nullable: true,
      editable: true,
      domain: null,
      defaultValue: null,
    },
    {
      name: "YEAR",
      type: "esriFieldTypeInteger",
      alias: "Year",
      sqlType: "sqlTypeOther",
      nullable: true,
      editable: true,
      domain: null,
      defaultValue: null,
    },
    {
      name: "VALUE",
      type: "esriFieldTypeDouble",
      alias: "Value",
      sqlType: "sqlTypeOther",
      nullable: true,
      editable: true,
      domain: null,
      defaultValue: null,
    },
  ],
};

